# Generated by Django 4.2.1 on 2023-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
